<?php

/**
 * BaseCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nome_fantasia
 * @property string $razao_social
 * @property integer $cpf_cnpj
 * @property string $endereco
 * @property string $cep
 * @property string $bairro
 * @property string $cidade
 * @property string $uf
 * @property string $responsavel
 * @property string $responsavel_cpf
 * @property string $responsavel_end
 * @property string $responsavel_cep
 * @property string $responsavel_bairro
 * @property string $responsavel_cidade
 * @property string $responsavel_uf
 * @property integer $situacao
 * @property Doctrine_Collection $Email
 * @property Doctrine_Collection $Telefone
 * @property Doctrine_Collection $Atendimento
 * @property Doctrine_Collection $Os
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getNomeFantasia()       Returns the current record's "nome_fantasia" value
 * @method string              getRazaoSocial()        Returns the current record's "razao_social" value
 * @method integer             getCpfCnpj()            Returns the current record's "cpf_cnpj" value
 * @method string              getEndereco()           Returns the current record's "endereco" value
 * @method string              getCep()                Returns the current record's "cep" value
 * @method string              getBairro()             Returns the current record's "bairro" value
 * @method string              getCidade()             Returns the current record's "cidade" value
 * @method string              getUf()                 Returns the current record's "uf" value
 * @method string              getResponsavel()        Returns the current record's "responsavel" value
 * @method string              getResponsavelCpf()     Returns the current record's "responsavel_cpf" value
 * @method string              getResponsavelEnd()     Returns the current record's "responsavel_end" value
 * @method string              getResponsavelCep()     Returns the current record's "responsavel_cep" value
 * @method string              getResponsavelBairro()  Returns the current record's "responsavel_bairro" value
 * @method string              getResponsavelCidade()  Returns the current record's "responsavel_cidade" value
 * @method string              getResponsavelUf()      Returns the current record's "responsavel_uf" value
 * @method integer             getSituacao()           Returns the current record's "situacao" value
 * @method Doctrine_Collection getEmail()              Returns the current record's "Email" collection
 * @method Doctrine_Collection getTelefone()           Returns the current record's "Telefone" collection
 * @method Doctrine_Collection getAtendimento()        Returns the current record's "Atendimento" collection
 * @method Doctrine_Collection getOs()                 Returns the current record's "Os" collection
 * @method Cliente             setId()                 Sets the current record's "id" value
 * @method Cliente             setNomeFantasia()       Sets the current record's "nome_fantasia" value
 * @method Cliente             setRazaoSocial()        Sets the current record's "razao_social" value
 * @method Cliente             setCpfCnpj()            Sets the current record's "cpf_cnpj" value
 * @method Cliente             setEndereco()           Sets the current record's "endereco" value
 * @method Cliente             setCep()                Sets the current record's "cep" value
 * @method Cliente             setBairro()             Sets the current record's "bairro" value
 * @method Cliente             setCidade()             Sets the current record's "cidade" value
 * @method Cliente             setUf()                 Sets the current record's "uf" value
 * @method Cliente             setResponsavel()        Sets the current record's "responsavel" value
 * @method Cliente             setResponsavelCpf()     Sets the current record's "responsavel_cpf" value
 * @method Cliente             setResponsavelEnd()     Sets the current record's "responsavel_end" value
 * @method Cliente             setResponsavelCep()     Sets the current record's "responsavel_cep" value
 * @method Cliente             setResponsavelBairro()  Sets the current record's "responsavel_bairro" value
 * @method Cliente             setResponsavelCidade()  Sets the current record's "responsavel_cidade" value
 * @method Cliente             setResponsavelUf()      Sets the current record's "responsavel_uf" value
 * @method Cliente             setSituacao()           Sets the current record's "situacao" value
 * @method Cliente             setEmail()              Sets the current record's "Email" collection
 * @method Cliente             setTelefone()           Sets the current record's "Telefone" collection
 * @method Cliente             setAtendimento()        Sets the current record's "Atendimento" collection
 * @method Cliente             setOs()                 Sets the current record's "Os" collection
 * 
 * @package    control_sys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cliente');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nome_fantasia', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('razao_social', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cpf_cnpj', 'integer', 14, array(
             'type' => 'integer',
             'length' => 14,
             ));
        $this->hasColumn('endereco', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('cep', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('bairro', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('cidade', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('uf', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('responsavel', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('responsavel_cpf', 'string', 13, array(
             'type' => 'string',
             'length' => 13,
             ));
        $this->hasColumn('responsavel_end', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('responsavel_cep', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('responsavel_bairro', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('responsavel_cidade', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('responsavel_uf', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('situacao', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Email', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('Telefone', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('Atendimento', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('Os', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}