<?php

/**
 * BaseOs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $telefone
 * @property integer $cliente_id
 * @property integer $atendimento_id
 * @property string $tipo
 * @property string $descricao
 * @property Cliente $Cliente
 * 
 * @method string  getTelefone()       Returns the current record's "telefone" value
 * @method integer getClienteId()      Returns the current record's "cliente_id" value
 * @method integer getAtendimentoId()  Returns the current record's "atendimento_id" value
 * @method string  getTipo()           Returns the current record's "tipo" value
 * @method string  getDescricao()      Returns the current record's "descricao" value
 * @method Cliente getCliente()        Returns the current record's "Cliente" value
 * @method Os      setTelefone()       Sets the current record's "telefone" value
 * @method Os      setClienteId()      Sets the current record's "cliente_id" value
 * @method Os      setAtendimentoId()  Sets the current record's "atendimento_id" value
 * @method Os      setTipo()           Sets the current record's "tipo" value
 * @method Os      setDescricao()      Sets the current record's "descricao" value
 * @method Os      setCliente()        Sets the current record's "Cliente" value
 * 
 * @package    control_sys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('os');
        $this->hasColumn('telefone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cliente_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('atendimento_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tipo', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cliente', array(
             'local' => 'cliente_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}