<?php

/**
 * BaseEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property integer $cliente_id
 * @property string $tipo
 * @property Cliente $Cliente
 * 
 * @method string  getEmail()      Returns the current record's "email" value
 * @method integer getClienteId()  Returns the current record's "cliente_id" value
 * @method string  getTipo()       Returns the current record's "tipo" value
 * @method Cliente getCliente()    Returns the current record's "Cliente" value
 * @method Email   setEmail()      Sets the current record's "email" value
 * @method Email   setClienteId()  Sets the current record's "cliente_id" value
 * @method Email   setTipo()       Sets the current record's "tipo" value
 * @method Email   setCliente()    Sets the current record's "Cliente" value
 * 
 * @package    control_sys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('email');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cliente_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tipo', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cliente', array(
             'local' => 'cliente_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}