<?php

/**
 * AtendimentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AtendimentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AtendimentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Atendimento');
    }
}