<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/18 02:13:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=CONTROLSYS;host=localhost',
  'username' => 'controlsys',
  'password' => '123',
  'name' => 'doctrine',
)),);
